### ISSUE TITLE
Git tag of releases

### ISSUE THREAD

**Issue by therefromhere** [unhaggle/django-memoize#33]
Could you start doing git tags of pypi releases again so it's easy to match up code changes with package releases?  The last git tag/GitHub release is currently 1.2.0 from 2015 (https://github.com/tvavrys/django-memoize/releases)

**Comment by tvavrys** [comment]
@therefromhere Sure. I'll try to update it.

**Comment by utek** [comment]
Those are being set now :) Closing this issue
